### ISSUE TITLE
advanced search tooltips

### ISSUE THREAD

**Issue by eightysteele** [VertNet/webapp#267]
things like "season" need a little explanation so that researchers know what they are searching for.

**Comment by laurarussell** [comment]
Info bubble tool tips in process.

**Comment by laurarussell** [comment]
Need info bubble text for Months.

**Comment by laurarussell** [comment]
Change info bubbles action to "click" instead of hover if possible.

**Comment by laurarussell** [comment]
Click value is currently used to redirect user to longer help page.  Leaving hover functionality as is for now.

**Comment by dbloom** [comment]
For Months bubble:

Search will identify all records contained within the range of months submitted.  Use numerical values 1 through 12.

**Comment by dbloom** [comment]
For all info bubbles that contain "Read more..."   I think the read more option is a little misleading as I would expect to read more about the field or content that I have questions about, and hence, looking at the info bubble.

Since all of those links go to the Advance Search Guide, can we change "Read more..." to "More tips..." or "More search tips..." or "More about search..."?

**Comment by laurarussell** [comment]
Based on Hangout conversation with @dbloom, removed most of the infobubbles and instead used placeholder text in the form boxes to display help tips.  Also added Advanced Search Guide link above the search box/advanced search options.

**Comment by laurarussell** [comment]
Fixed by #563 and #575
