### ISSUE TITLE
Time to return d/l records sets is long(?) 

### ISSUE THREAD

**Issue by dbloom** [VertNet/webapp#350]
When testing data sets for another issue I needed to download quite a few data sets.  I downloaded records sets ranging from 15k to 55k.  Those in the ballpark of 25k records took about 10-15 minutes to return.  They records sets in the ballpark of 50k records took between15 and 30 minutes to return (two took more than 25 minutes).

Should it take VN so long to compile a file and notify the user?  I wonder how long it'll take to d/l 100k records or more.

**Comment by laurarussell** [comment]
Dave is this still an issue or can this be closed?

**Comment by tucotuco** [comment]
Downloads have been completely refactored with the deprecation of the Files API. Request time and result delivery time are now given in the email notification that the file is ready. Expect about 10s per 1000 records, on average. It is not really feasible to alert the user how long it will take to download the results, because the count is not known until the query pages through them all. By then, it is ready for download. I made a count API which can get counts much faster (about 1s per 1000 records), but that is too slow for a user to wait for in a UI. Still, it is useful for us if we really want to know how many records match in the index. It is documented only esoterically by the code for now, and results are only written to CartoDB as type='count'. If anyone thinks this should be part of the public API offerings, let me know and I will implement an email sending mechanism with the results, similar to downloads.
