### ISSUE TITLE
Advanced searches seeking tissues return records that are not tissues.

### ISSUE THREAD

**Issue by dbloom** [VertNet/webapp#421]
From portal feedback form (comments below feedback):

Question                 Answer
First Name               Chris
Last Name                Conroy
Email Address            ondatra@berkeley.edu
What would you like to tell us about (select one)?               General comments or questions
Let us know how we can get you started (select one):
Institution or Collection Name
Please give us your feedback, ask your question, or describe your issue. Use as much detail as necessary. You can attach a screen capture and other documentation in the next field below.        I searched for Chrysochloris and checked the tissue box. I got back two specimens from MVZ that do not have "tissue". What they have is a record of their skins having been sampled for a study on iridescence in their fur. These records should not come up like this. Also, these specimens have a citation in arctos. In the Darwin Core records, that citation is a hyperlink, but it does not take one to the citation in Arctos. It just goes back to the specimen record.
Attach a screen capture or other relevant documentation.

COMMENTS:  I suspect this has to do with a keyword search for the list terms that could indicate that a record is a "tissue" that Carla created.  If so, did Chris just find the one-off that is contrary to our rule or do queries using the "Tissues" query box in Advanced Search return non-tissue records on a regular basis?  Weak link on our part?  Need to remove "sample" from keyword list?  Explanation needed that not all records returned may be tissues (man, I hope not)?  Other options?

**Comment by laurarussell** [comment]
Sample is part of our keyword list for tissue.  Not sure we'd want to remove that. Bi-weekly group discussion?

**Comment by tucotuco** [comment]
A look in BigQuery reveals that there are around 28000 records that have 'sample' in the preparations field, and 4876 records that have 'sample' without having 'tissue', 'frozen', 'liver', 'kidney', 'spleen', 'heart', 'toe', 'muscle', 'lung', 'blood', 'ethanol', 'etoh', or 'alcohol' in the preparations field. 

There are 344 distinct strings in preparations among the 4876 records, and the sample types among them are mostly skin, skull, skeleton, feather, dentary, fur, and the like. Therefore I think it is safe to remove 'sample' as a tissue criterion, since it definitely returns records that are not tissues.

Closing this issue and creating a new one for the link behavior described.
