### ISSUE TITLE
Institutions List not showing

### ISSUE THREAD

**Issue by tucotuco** [VertNet/webapp#582]
From some locations (Carnegie Museum among them), it appears that the call to CartoDB to fill the institutions list is failing to return. Troubleshooting by IT at CM revealed the following:

"It appears as though that frame in the website is pulled from vertnet.cartodb.org. I’m asuming it is part of an API that you’re using that is hosted on Amazon. The issue is that different IP addresses for that particular API are pulled, which makes me believe that it is load balanced on the AWS side. We’ve noticed that some of the IP addresses that we receive will allow the code to execute properly and some IP addresses do not (looks like that specific section just runs a SQL query).
 
It does not appear to be a compatability issue. From my viewpoint it looks to be an issue with vertnet.cartodb.org’s AWS configuration."

One last-resort option is to hardcode the list. But that is a pain to have to maintain and requires a redeployment.

Notify Steve Rogers when resolved or for testing.

**Comment by dbloom** [comment]
Related to this issue.  This in from Werneke at Auburn.

"I'm sure someone has probably brought this up by now, but the advanced search for VertNet is automatically searching for Institution code in addition to any other fields you choose. I'm unable to clear this out unless I refresh the page and delete the search term in the simple search bar. I'm using the Chrome browser."

I've ask David to provide us with some example queries that didn't work as expected because of this, if he has the chance.

**Comment by laurarussell** [comment]
Comment https://github.com/VertNet/webapp/issues/582#issuecomment-148210586 addressed by https://github.com/VertNet/webapp/commit/bdbfbed6531346eb87c448760fb49fe158b8479f

Comment https://github.com/VertNet/webapp/issues/582#issue-111466958 addressed in https://github.com/VertNet/webapp/commit/3590f5b55a11ab7cca8f901d2440a0226bf4b284 by adding https to CartoDB pull.  Needs to be tested by those who previously had issues.

**Comment by tucotuco** [comment]
Functions correctly at CM.
