### ISSUE TITLE
Add citation formula to Rights tab

### ISSUE THREAD

**Issue by laurarussell** [VertNet/webapp#593]
Use the recommended citation from the norms to auto-produce record citation on the rights tab on search record detail.

**Comment by dbloom** [comment]
SINGLE DATASET
GENERAL FORMAT
[dataset name]. [data publisher]. [link to dataset] (accessed on [date])
EXAMPLE
Cowan Tetrapod Collection at the University of British Columbia Beaty Biodiversity Museum (UBCBBM). University of British Columbia. http://ipt.vertnet.org:8080/ipt/resource.do?r=ubc_bbm_ctc_birds (accessed on 2014-07-28)

http://www.vertnet.org/resources/help.html#t-tab4

**Comment by tucotuco** [comment]
Added in https://github.com/VertNet/post-harvest-processor/commit/59f8c525fec57e34b3b7d323da76239364905e74.
Added post-harvest processing for citation and bibliographiccitation to make them consistent across all records in the data store. Made both formats more specific than given in the VertNet norms document. Specifically, for citation:
[title]. [orgname]. [source_url]. Data set DOI: [doi] (published on [pubdate])

For bibligraphiccitation:
[bestid]. [citation]

where bestid is occurrenceID if that exists, otherwise id if that exists, otherwise catalognumber.
