### ISSUE TITLE
'count' taskqueue corrupt?

### ISSUE THREAD

**Issue by jotegui** [VertNet/webapp#596]
I cannot access the 'count' task queue data from the cloud console. Every time I try, I get a `Failed to load` message. Is it just me? It says there are 3 tasks in the queue which are probably not going to finish ever, but I cannot check that out and remove them if so...

https://console.cloud.google.com/appengine/taskqueues/count?project=vertnet-portal

**Comment by tucotuco** [comment]
I had a "failed" to load due to lack of permissions when I tried to load
from the link in this issue. Then I clicked on the count task queue in the
console and was able to see them (same URL). Strange.

Two of the task queues are from 216 days ago. One is from 11 days ago. I
removed all three.

https://console.cloud.google.com/appengine/taskqueues/count?project=vertnet-portal

**Comment by tucotuco** [comment]
This seems to no longer be a problem.
