### ISSUE TITLE
Query Element Layout

### ISSUE THREAD

**Issue by tucotuco** [VertNet/webapp#606]
Already so much better than the production version. The Institution selection at the top is head-banging good. Why didn't we do that before?

Having it there makes it more obvious that another improvement would be to put all the record identifying query elements on the same row right under it. Thus, just under InstitutionCode, in order:
CollectionCode, CatalogNumber, OccurrenceID, FieldNumber, RecordNumber

Then, on the next row, so that RecordNumber lies directly above RecordedBy:
BasisOfRecord, Preparation, Sex, LifeStage, RecordedBy

**Comment by robgur** [comment]
+1

**Comment by laurarussell** [comment]
So am I removing License completely?

**Comment by tucotuco** [comment]
I didn't want to make that call, I just wanted to propose how the first
three rows look. To me license is a medium-dubious one to want to query on.

**Comment by laurarussell** [comment]
They only place for it now would be down on startdayofyear row.  Has License doesn't really seem to me to be useful anymore because everybody will have a license so I didn't add it.  It would seem like people would want to select/search for a specific license, but the content can be so varied.  I'm fine with removing it.  I added it previously just cause it was something we had talked about in the past.

**Comment by tucotuco** [comment]
It can be decided in the grand discussion on which of the many now-indexed
fields to enable in queries.

**Comment by laurarussell** [comment]
Other fields have been moved, https://github.com/VertNet/webapp/commit/f3ff9f4355d3cb856da81ac6236615f16795ba05.  Not really room for license now.

**Comment by tucotuco** [comment]
Like very much. Confirmed good.
