### ISSUE TITLE
Portal Downloads Not Working

### ISSUE THREAD

**Issue by laurarussell** [VertNet/webapp#632]
Alerted via a tweet from a user and then via feedback form that downloads both <1000 and >1000 are not working.  Testing confirms in all browsers that this is an issue.  API downloads do work however.  API is still old-style...Portal using service now.

**Comment by tucotuco** [comment]
The deployment to prod yesterday was the first time I did it with 

```
gcloud app deploy portal-web.yaml --version prod --promote
```

from a portal-web.yaml file copied and adapted from https://github.com/VertNet/portal-web/blob/master/portal-web.yaml. In that file, the download service was commented out. I uncommented it and redeployed to all versions. Download seems to be working, aside from some timeouts apparently due to the flood of backlogged downloads being fired up again.

Relevant code in portal-web.yaml was:

```
- url: /service/download.*
  script: vertnet.service.download.api
```
